FROM apache/spark:3.5.0

# Installer Python et pip
USER root
RUN apt-get update && apt-get install -y python3 python3-pip

# Installer PySpark (et kafka lib pour streaming)
RUN pip3 install pyspark==3.5.0 kafka-python

# Revenir à l'utilisateur spark
USER spark

WORKDIR /opt/spark/work-dir
